# Generated by Django 3.2.13 on 2022-07-04 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20220701_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='partner.warehouse'),
        ),
    ]
